### ISSUE TITLE
wrong output of duration in tooltip

### ISSUE THREAD

**Issue by hanswurscht** [alexiri/splunk-gantt#12]
Hi,

splunk caclulates a duration field when using transactions. This field has a decimal point in it and is presented in seconds.
Example: duration=1.091

However this duration is displayed in the tooltip as 91s.
Using something like " ... | eval duration=round(duration,0)" in splunk makes splunk-gantt display the correct duration of 1s.

Maybe this has something todo with localization. The language of my operating system is set to german. There could be an issue with . and ,

Thanks!

**Comment by stash1001** [comment]
We also have that issue.  I also use round(duration,0)  Adding subsecond transactions is something thats also of interest to us.
