### ISSUE TITLE
Suggested sanity check for token handling

### ISSUE THREAD

**Issue by thibodux** [alexiri/splunk-gantt#16]
The click handler when `tokenField` and `tokenLabel` is not very robust.  It will throw errors if you click on the legend or y-axis.  My suggested checks to include would confirm the 'data' and 'tokenField` values are defined before trying to set the token.

`if (typeof data !== 'undefined' && typeof data[this.settings.get('tokenField')] !== 'undefined')`

**Comment by alexiri** [comment]
Thanks for the suggestion!
